# Generated by Django 5.2.6 on 2025-11-24 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cusca', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='bachillerato_anio',
            field=models.CharField(blank=True, choices=[('1', 'Primer año'), ('2', 'Segundo año'), ('3', 'Tercer año (solo Técnico)')], max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='bachillerato_tipo',
            field=models.CharField(blank=True, choices=[('general', 'General'), ('tecnico', 'Técnico Vocacional')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='grado',
            field=models.CharField(blank=True, choices=[('kinder', 'Kínder'), ('preparatoria', 'Preparatoria'), ('1', 'Primero'), ('2', 'Segundo'), ('3', 'Tercero'), ('4', 'Cuarto'), ('5', 'Quinto'), ('6', 'Sexto'), ('7', 'Séptimo'), ('8', 'Octavo'), ('9', 'Noveno'), ('bachillerato', 'Bachillerato')], max_length=20, null=True),
        ),
    ]
