# Generated by Django 5.2.6 on 2025-11-25 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cusca', '0003_guia'),
    ]

    operations = [
        migrations.AddField(
            model_name='guia',
            name='materia',
            field=models.CharField(choices=[('matematicas', 'Matemáticas'), ('lengua_literatura', 'Lengua y Literatura'), ('ciencias_sociales', 'Ciencias Sociales'), ('ingles', 'Inglés (Lengua Extranjera)'), ('educacion_fisica', 'Educación Física'), ('moral_urbanidad_civica', 'Moral, Urbanidad y Cívica / Ética y Ciudadana'), ('educacion_tecnologica', 'Educación Tecnológica / Informática'), ('historia', 'Historia'), ('orientacion_para_la_vida', 'Orientación para la Vida'), ('biologia', 'Biología'), ('fisica', 'Física'), ('quimica', 'Química'), ('filosofia', 'Filosofía'), ('gestion_empresarial', 'Gestión Empresarial'), ('servicio_social', 'Servicio Social'), ('teoria_del_conocimiento', 'Teoría del Conocimiento')], default='matematicas', max_length=64),
            preserve_default=False,
        ),
    ]
