# Generated by Django 5.2.6 on 2025-11-27 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cusca', '0005_forumpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='forumpost',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
