# Generated by Django 5.2.6 on 2025-11-27 03:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cusca', '0006_forumpost_views'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Título de la noticia', max_length=255)),
                ('content', models.TextField(help_text='Contenido de la noticia')),
                ('is_active', models.BooleanField(default=True, help_text='Marcar para mostrar en la página')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Noticia Estudiantil',
                'verbose_name_plural': 'Noticias Estudiantiles',
                'ordering': ['-created_at'],
            },
        ),
    ]
